apiVersion: v1
kind: ConfigMap
metadata:
  name: opencode-config
  namespace: agentq
data:
  opencode.json: |
    {
      "mcp": {
        "Astro docs": {
          "type": "remote",
          "url": "https://mcp.docs.astro.build/mcp",
          "enabled": true
        },
        "playwright": {
          "type": "remote",
          "url": "http://playwright-mcp:3333/mcp",
          "enabled": true
        },
        "context7": {
          "type": "remote",
          "url": "https://mcp.context7.com/mcp",
          "enabled": true
        }
      }
    }
